#!/bin/bash

pushd ..

if [ ! -f .vimrc ]; then
    ln -s config/.vimrc .
else
    rm .vimrc
    ln -s config/.vimrc .
fi

if [ ! -f .gitconfig ]; then
    ln -s config/.gitconfig .
else
    rm .gitconfig
    ln -s config/.gitconfig .
fi

if [ ! -f .bashrc ]; then
    ln -s config/.bashrc .
else
    rm .bashrc
    ln -s config/.bashrc .
fi
source ~/.bashrc
popd

# Check to see if Vundle is already installed
if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi
